# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/groquette',
                'doc_host': 'https://simveit.github.io',
                'git_url': 'https://github.com/simveit/groquette',
                'lib_path': 'groquette'},
  'syms': {'groquette.core': {}}}
