# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['models']

# %% ../nbs/00_core.ipynb 3
from groq import Groq

# %% ../nbs/00_core.ipynb 5
models = "llama3-70b-8192", "mixtral-8x7b-32768", "llama3-8b-8192", "gemma-7b-it"
